name: ci

on:
  push:
    branches: [main]
  pull_request:

permissions:
  contents: read
  security-events: write

env:
  TF_IN_AUTOMATION: "true"
  TF_INPUT: "0"

jobs:
  fmt:
    name: terraform fmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.9.8"
      - run: terraform fmt -check -recursive -diff

  validate:
    name: validate (${{ matrix.dir }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        dir: [modules/s3-secure-bucket, bootstrap, stacks/web-db]
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.9.8"
      - run: terraform init -backend=false
        working-directory: ${{ matrix.dir }}
      - run: terraform validate
        working-directory: ${{ matrix.dir }}

  tfsec:
    name: tfsec
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: aquasecurity/tfsec-action@v1.0.3
        with:
          working_directory: .
          additional_args: --minimum-severity HIGH --concise-output

  checkov:
    name: checkov
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: bridgecrewio/checkov-action@v12
        with:
          directory: .
          config_file: .checkov.yaml
          output_format: cli,sarif
          output_file_path: console,results.sarif
      - uses: github/codeql-action/upload-sarif@v3
        if: always()
        with:
          sarif_file: results.sarif
        continue-on-error: true

  policy:
    name: conftest verify
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: install conftest
        run: |
          set -euo pipefail
          VERSION=0.56.0
          curl -sSL "https://github.com/open-policy-agent/conftest/releases/download/v${VERSION}/conftest_${VERSION}_Linux_x86_64.tar.gz" | tar xz conftest
          sudo mv conftest /usr/local/bin/
      - run: conftest verify -p policy
